### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [trueDKstudent/AL304_wrist_watch#1]
Hello!

I found this project from https://hackaday.io/project/197471-hdsp-2000-wrist-watch

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and images in any purpose?
It would be great to see any popular open source license.

**Comment by trueDKstudent** [comment]
Hi, I've just added MIT license to repo.
P.S. sorry for late responce, I've only now notices this message.

**Comment by vazhnov** [comment]
MIT would be awesome!

@trueDKstudent , probably you've forgotten to push the change — the last commit is still 4 months ago…

**Comment by trueDKstudent** [comment]
But license is on place. In your first message you reffered to hdsp-2000 proj. but the message itself is attached to AL301 repository. So do you need license info for hdsp-2000 or AL301 proj?

**Comment by vazhnov** [comment]
Oops, yes, https://github.com/trueDKstudent/HDSP_watch
Somehow I've created a ticket in wrong repository.
Thank you very much!
